"""test

Revision ID: 11f6cb9b30c3
Revises: 816112cf9352
Create Date: 2026-02-21 21:27:59.810273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f6cb9b30c3'
down_revision: Union[str, Sequence[str], None] = '816112cf9352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
